### ISSUE TITLE
Unknown type name GtkFileChooserNative (Ubuntu 16.04 based system)

### ISSUE THREAD

**Issue by salamanderrake** [her001/Asma#14]
Got it to configure now I am running into this issue.

> asma/builddir$ ninja
[1/2] Compiling C object 'src/asma@exe/prefs.c.o'.
FAILED: src/asma@exe/prefs.c.o 
cc  -Isrc/asma@exe -Isrc -I../src -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -pthread -MMD -MQ 'src/asma@exe/prefs.c.o' -MF 'src/asma@exe/prefs.c.o.d' -o 'src/asma@exe/prefs.c.o' -c ../src/prefs.c
../src/prefs.c:133:2: error: unknown type name 'GtkFileChooserNative'; did you mean 'GtkFileChooserAction'?
        GtkFileChooserNative *native;
        ^~~~~~~~~~~~~~~~~~~~
        GtkFileChooserAction
/usr/include/gtk-3.0/gtk/gtkfilechooser.h:60:3: note: 'GtkFileChooserAction' declared here
} GtkFileChooserAction;
  ^
../src/prefs.c:138:11: warning: implicit declaration of function 'gtk_file_chooser_native_new' is invalid in C99 [-Wimplicit-function-declaration]
        native = gtk_file_chooser_native_new("Select Arma 3 Folder",
                 ^
../src/prefs.c:138:9: warning: incompatible integer to pointer conversion assigning to 'GtkFileChooserAction *' from 'int' [-Wint-conversion]
        native = gtk_file_chooser_native_new("Select Arma 3 Folder",
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/prefs.c:143:8: warning: implicit declaration of function 'gtk_native_dialog_run' is invalid in C99 [-Wimplicit-function-declaration]
        res = gtk_native_dialog_run(GTK_NATIVE_DIALOG (native));
              ^
../src/prefs.c:143:30: warning: implicit declaration of function 'GTK_NATIVE_DIALOG' is invalid in C99 [-Wimplicit-function-declaration]
        res = gtk_native_dialog_run(GTK_NATIVE_DIALOG (native));
                                    ^
4 warnings and 1 error generated.
ninja: build stopped: subcommand failed.

GTK 3 Dev files version: libgtk-3-dev/xenial-updates,now 3.18.9-1ubuntu3.3 amd64

**Comment by her001** [comment]
It should work now. You had a GTK version which was too old, but in this case I am okay with lowering the requirements.
