### ISSUE TITLE
Can this software to download and update MODs from the workshop?

### ISSUE THREAD

**Issue by EgoBrainProgrammer** [her001/Asma#16]
There is a main arma 3 launcher function - to download and update arma mods, because steam client cant to do it.
Does your program support this feature?

**Comment by Preisschild** [comment]
Workshop mods gets updated over steam AFAIK, the Windows launcher just shows the process

**Comment by EgoBrainProgrammer** [comment]
Is this utility exist for Linux?

**Comment by her001** [comment]
In the Steam client (or signed in to Steam in a web browser) you can subscribe to workshop items, which will then be downloaded in the native Linux Steam client. You do not need a launcher to handle this functionality, though it does potentially make it smoother.

For an example, see the CBA [workshop page](https://steamcommunity.com/sharedfiles/filedetails/?id=450814997). Click subscribe and the download will begin in the Steam client.

**Comment by EgoBrainProgrammer** [comment]
Ok. Thank you for answer.
In case of Windows the downloading doesn't start after subscribe, you should to start arma3launcher first.
