### ISSUE TITLE
Project name change

### ISSUE THREAD

**Issue by nixi-awoo** [her001/Asma#5]
@busquetsaguilopau decided to change the project name.

Possible new names for inspiration:
- ASMA `does not have a meaning`
- SAL `Simple Arma Launcher`
- SALL `Simple Arma Launcher for Linux`
- SA3L `Simple Arma 3 Launcher`

Feedback from users is appreciated.
Post your thoughts / suggestions as a comment on this issue.

**Comment by codingHahn** [comment]
SALL is best. My opinion

**Comment by MustD** [comment]
SA3L for me

**Comment by WaKeMaTTa** [comment]
I propose `A3LL` (**A**rma **3** **L**inux **L**auncher)

**Comment by WaKeMaTTa** [comment]
or `A3UL` (**A**rma **3** **U**nix **L**auncher) [if you want to suport OSX too]

**Comment by her001** [comment]
If we are to stick to ASMA, which seems most likely at the moment, we should at least standardize the capitalization. Do we want `ASMA`, `asma`, or `Asma`?

**Comment by her001** [comment]
I've decided to stick with `Asma`.
